baseURL = "https://cv.agnesepoikane.com/"
languageCode = "en-us"
title = "CV Agnese Poikane-Pucoka"
theme = "pulp"

[params]
    author = "Agnese Poikane-Pucoka"
    description = """ 
<b>Data & Research Analyst | Coach | Consultant | Mentor </b>
<br></br>
Keywords: Public Safety & Criminal Justice, Crime Data Visualization, Deviant Behavior & Thinking, Social Development, Social Innovation, Philanthropy & Social Entrepreneurship, Customer Experience, Behavioral Analytics, Cognitive Biases, Growth Mindset
<br></br>
    """
    publicationYear = "2019"
    avatar = "avatar.png"


[[menu.main]]
    identifier = "github"
    pre = "<i class='fab fa-github fa-lg' title='GitHub'></i>"
    url = "https://github.com/puchokagnese"
    weight = 10

[[menu.main]]
    identifier = "linkedin"
    pre = "<i class='fab fa-linkedin fa-lg' title='LinkedIn'></i>"
    url = "https://www.linkedin.com/in/agnese-poikane-pucoka/"
    weight = 20

[[menu.main]]
    identifier = "facebook"
    pre = "<i class='fab fa-facebook-f' title='Facebook'></i>"
    url = "https://www.facebook.com/agnese.poikane"
    weight = 30

[[menu.main]]
    identifier = "instagram"
    pre = "<i class='fab fa-instagram fa-lg' title='Instagram'></i>"
    url = "https://www.instagram.com/poikaneagnese/"
    weight = 40

[[menu.main]]
    identifier = "blog"
    #name = "Data Blog" #If display text link, cancel comment out
    pre = "<i class='fas fa-book-open' title='Blog'></i>"
    #url = "/blog"
    weight = 50



