baseURL = "https://cv.agnesepoikane.com/"
languageCode = "en-us"
title = "CV Agnese Poikane-Pucoka"
theme = "pulp"

[params]
    author = "Agnese Poikane-Pucoka"
    description = """ 
<b>DATA ANALYST &nbsp;&nbsp; | &nbsp;&nbsp; MINDSET COACH</b>
<br></br>
Interests: behavioral analytics, UX research, crime data visualization, cognitive biases and growth mindset 
<br></br>
    """
    publicationYear = "2019"
    avatar = "avatar.png"


[[menu.main]]
    identifier = "data analysis"
    #name = "Data Blog" #If display text link, cancel comment out
    pre = "<i class='fas fa-signal' title='Data Analysis'></i>"
    #url = "/data"
    weight = 10

[[menu.main]]
    identifier = "github"
    pre = "<i class='fab fa-github fa-lg' title='GitHub'></i>"
    url = "https://github.com/puchokagnese"
    weight = 20

[[menu.main]]
    identifier = "linkedin"
    pre = "<i class='fab fa-linkedin fa-lg' title='LinkedIn'></i>"
    url = "https://www.linkedin.com/in/agnese-poikane-pucoka/"
    weight = 30

[[menu.main]]
    identifier = "instagram"
    pre = "<i class='fab fa-instagram fa-lg' title='Instagram'></i>"
    url = "https://www.instagram.com/poikaneagnese/"
    weight = 40

[[menu.main]]
    identifier = "mindset"
    #name = "Blog" #If display text link, cancel comment out
    pre = "<i class='fa fa-brain' title='Mindset'></i>"
    #url = "/coaching"
    weight = 50

