baseURL = "https://cv.agnesepoikane.com/"
languageCode = "en-us"
title = "CV Agnese Poikane-Pucoka"
theme = "pulp"

[params]
    author = "Agnese Poikane-Pucoka"
    description = """ 
<b>DATA ANALYST &nbsp;&nbsp; | &nbsp;&nbsp; MINDSET COACH</b>
<br></br>
Interests: user behaviour analytics, crime data analysis, data visualization, sociology of crime and deviance, cognitive biases and mindset 
<br></br>
    """
    publicationYear = "2019"
    avatar = "avatar.png"


[[menu.main]]
    identifier = "data"
    #name = "Data Blog" #If display text link, cancel comment out
    pre = "<i class='fas fa-signal' title='Data Analysis'></i>"
    #url = "/data"
    weight = 10

[[menu.main]]
    identifier = "github"
    pre = "<i class='fab fa-github fa-lg' title='GitHub'></i>"
    url = "https://github.com/puchokagnese"
    weight = 20

[[menu.main]]
    identifier = "kaggle"
    pre = "<i class='fab fa-kaggle fa-lg' title='Kaggle'></i>"
    url = "https://www.kaggle.com/puchokagnese"
    weight = 30

[[menu.main]]
    identifier = "linkedin"
    pre = "<i class='fab fa-linkedin fa-lg' title='LinkedIn'></i>"
    url = "https://www.linkedin.com/in/agnese-poikane-pucoka/"
    weight = 40

[[menu.main]]
    identifier = "instagram"
    pre = "<i class='fab fa-instagram fa-lg' title='Instagram'></i>"
    url = "https://www.instagram.com/poikaneagnese/"
    weight = 50

[[menu.main]]
    identifier = "goodreads"
    pre = "<i class='fab fa-goodreads-g' title='Goodreads'></i>"
    url = "https://www.goodreads.com/user/show/22833723-agnese"
    weight = 60

[[menu.main]]
    identifier = "coaching"
    #name = "Blog" #If display text link, cancel comment out
    pre = "<i class='fa fa-heart' title='Coaching'></i>"
    #url = "/coaching"
    weight = 70

